package annotation

var futexOps = map[int]string{
	0:        "FUTEX_WAIT",
	1:        "FUTEX_WAKE",
	2:        "FUTEX_FD",
	3:        "FUTEX_REQUEUE",
	4:        "FUTEX_CMP_REQUEUE",
	5:        "FUTEX_WAKE_OP",
	6:        "FUTEX_LOCK_PI",
	7:        "FUTEX_UNLOCK_PI",
	8:        "FUTEX_TRYLOCK_PI",
	9:        "FUTEX_WAIT_BITSET",
	10:       "FUTEX_WAKE_BITSET",
	11:       "FUTEX_WAIT_REQUEUE_PI",
	12:       "FUTEX_CMP_REQUEUE_PI",
	128:      "FUTEX_PRIVATE_FLAG|FUTEX_WAIT",
	128 | 1:  "FUTEX_PRIVATE_FLAG|FUTEX_WAKE",
	128 | 2:  "FUTEX_PRIVATE_FLAG|FUTEX_FD",
	128 | 3:  "FUTEX_PRIVATE_FLAG|FUTEX_REQUEUE",
	128 | 4:  "FUTEX_PRIVATE_FLAG|FUTEX_CMP_REQUEUE",
	128 | 5:  "FUTEX_PRIVATE_FLAG|FUTEX_WAKE_OP",
	128 | 6:  "FUTEX_PRIVATE_FLAG|FUTEX_LOCK_PI",
	128 | 7:  "FUTEX_PRIVATE_FLAG|FUTEX_UNLOCK_PI",
	128 | 8:  "FUTEX_PRIVATE_FLAG|FUTEX_TRYLOCK_PI",
	128 | 9:  "FUTEX_PRIVATE_FLAG|FUTEX_WAIT_BITSET",
	128 | 10: "FUTEX_PRIVATE_FLAG|FUTEX_WAKE_BITSET",
	128 | 11: "FUTEX_PRIVATE_FLAG|FUTEX_WAIT_REQUEUE_PI",
	128 | 12: "FUTEX_PRIVATE_FLAG|FUTEX_CMP_REQUEUE_PI",
	256:      "FUTEX_CLOCK_REALTIME|FUTEX_WAIT",
	256 | 1:  "FUTEX_CLOCK_REALTIME|FUTEX_WAKE",
	256 | 2:  "FUTEX_CLOCK_REALTIME|FUTEX_FD",
	256 | 3:  "FUTEX_CLOCK_REALTIME|FUTEX_REQUEUE",
	256 | 4:  "FUTEX_CLOCK_REALTIME|FUTEX_CMP_REQUEUE",
	256 | 5:  "FUTEX_CLOCK_REALTIME|FUTEX_WAKE_OP",
	256 | 6:  "FUTEX_CLOCK_REALTIME|FUTEX_LOCK_PI",
	256 | 7:  "FUTEX_CLOCK_REALTIME|FUTEX_UNLOCK_PI",
	256 | 8:  "FUTEX_CLOCK_REALTIME|FUTEX_TRYLOCK_PI",
	256 | 9:  "FUTEX_CLOCK_REALTIME|FUTEX_WAIT_BITSET",
	256 | 10: "FUTEX_CLOCK_REALTIME|FUTEX_WAKE_BITSET",
	256 | 11: "FUTEX_CLOCK_REALTIME|FUTEX_WAIT_REQUEUE_PI",
	256 | 12: "FUTEX_CLOCK_REALTIME|FUTEX_CMP_REQUEUE_PI",
	384:      "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_WAIT",
	384 | 1:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_WAKE",
	384 | 2:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_FD",
	384 | 3:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_REQUEUE",
	384 | 4:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_CMP_REQUEUE",
	384 | 5:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_WAKE_OP",
	384 | 6:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_LOCK_PI",
	384 | 7:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_UNLOCK_PI",
	384 | 8:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_TRYLOCK_PI",
	384 | 9:  "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_WAIT_BITSET",
	384 | 10: "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_WAKE_BITSET",
	384 | 11: "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_WAIT_REQUEUE_PI",
	384 | 12: "FUTEX_CLOCK_REALTIME|FUTEX_PRIVATE_FLAG|FUTEX_CMP_REQUEUE_PI",
}

func AnnotateFutexOp(arg Arg, pid int) {
	if s, ok := futexOps[int(arg.Raw())]; ok {
		arg.SetAnnotation(s, true)
	} else {
		AnnotateHex(arg, pid)
	}
}
