name: golangci-lint
on:
  pull_request:
permissions:
  contents: read
  pull-requests: read
jobs:
  golangci:
    name: Run golangci-lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true
          cache-dependency-path: go.sum
      - run: make headers
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3.2.0
        with:
          args: --timeout 3m --verbose
